export const AUTHENTICATION_TOKEN = 'authentication_token'
export const CALLBACK_URL = 'callbackUrl'
export const ACCESS_TOKEN = 'access_token'
export const TOKEN_TYPE = 'token_type'
export const ORIGINAL_PATH = 'originalPath'
export const DEFAULT_PATH = '/'